#!/usr/bin/env python3
"""Generate `bootloader/include/public_key.h` from `keys/public_key.pem`.

The C header exposes the public key as a 64-byte concatenation of the
affine point coordinates ``[X(32) || Y(32)]`` in big-endian, which is
exactly the format consumed by ``uECC_verify`` for the SECP256R1 curve.

Run via ``make keys`` (it depends on the PEM file, so re-running it after
key rotation forces the bootloader to be rebuilt against the new key).
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

try:
    from ecdsa import VerifyingKey
except ImportError:  # pragma: no cover
    sys.stderr.write(
        "error: missing dependency 'ecdsa'. Install with:\n"
        "    python -m pip install -r tools/requirements.txt\n"
    )
    sys.exit(2)


def emit(pub_pem: Path, out_h: Path) -> None:
    if not pub_pem.exists():
        sys.stderr.write(
            f"error: {pub_pem} not found. Run 'make keys' first.\n"
        )
        sys.exit(1)

    vk = VerifyingKey.from_pem(pub_pem.read_bytes())
    raw = vk.to_string()  # 64 bytes: X(32) || Y(32), big-endian
    if len(raw) != 64:
        sys.stderr.write(f"error: expected 64-byte raw key, got {len(raw)}\n")
        sys.exit(1)

    rows = []
    for i in range(0, 64, 8):
        rows.append(
            "    " + ", ".join(f"0x{b:02x}" for b in raw[i : i + 8]) + ","
        )
    body = "\n".join(rows)

    import hashlib
    fp = hashlib.sha256(raw).digest()
    fp_rows = []
    for i in range(0, 32, 8):
        fp_rows.append(
            "    " + ", ".join(f"0x{b:02x}" for b in fp[i : i + 8]) + ","
        )
    fp_body = "\n".join(fp_rows)

    header = (
        "/*\n"
        " * AUTO-GENERATED by tools/embed_pubkey.py.  DO NOT EDIT BY HAND.\n"
        " *\n"
        f" * Source: {pub_pem.as_posix()}\n"
        " * Format: SECP256R1 public point [X(32) || Y(32)] big-endian, raw.\n"
        " *         This is the byte order consumed by uECC_verify().\n"
        " */\n"
        "#ifndef PUBLIC_KEY_H\n"
        "#define PUBLIC_KEY_H\n"
        "\n"
        "#include <stdint.h>\n"
        "\n"
        "static const uint8_t public_key_xy[64] = {\n"
        f"{body}\n"
        "};\n"
        "\n"
        "/* SHA-256 fingerprint of public_key_xy for runtime integrity checks */\n"
        "static const uint8_t public_key_sha256[32] = {\n"
        f"{fp_body}\n"
        "};\n"
        "\n"
        "#endif /* PUBLIC_KEY_H */\n"
    )

    out_h.parent.mkdir(parents=True, exist_ok=True)
    out_h.write_text(header)
    print(f"Wrote {out_h} ({len(raw)} key bytes)")


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--pubkey", default="keys/public_key.pem", help="Public key PEM input"
    )
    parser.add_argument(
        "--out",
        default="bootloader/include/public_key.h",
        help="Output C header",
    )
    args = parser.parse_args()
    emit(Path(args.pubkey), Path(args.out))


if __name__ == "__main__":
    main()
